version = 0.1

[1]
[1.global]
[1.global.parameters]
stack_name = "hello-sam-01"
s3_prefix = "hello-sam-01"
s3_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1snr9i1u4cl8g"
region = "ap-southeast-1"

[1.deploy]
[1.deploy.parameters]
template = "packaged-testing.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""

# ############################################## #

[2]
[2.global]
[2.global.parameters]
stack_name = "hello-sam-01-prod"
s3_prefix = "hello-sam-01-prod"
s3_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1crczg2r0iemm"
region = "ap-southeast-1"

[2.deploy]
[2.deploy.parameters]
template = "packaged-prod.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""

# ############################################## #

[pipeline]
[pipeline.deploy]
[pipeline.deploy.parameters]
stack_name = "monorepo-pipeline"
s3_prefix = "monorepo-pipeline"
resolve_s3 = true
fail_on_empty_changeset = false
template = "codepipeline.yaml"
capabilities = "CAPABILITY_IAM"
